// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXowVkYvAoAFQ-6PvjIb0xCTPR_neInWM',
    appId: '1:433354340786:android:36a3fbba05d6088ca54cab',
    messagingSenderId: '433354340786',
    projectId: 'fir-learning-95afb',
    storageBucket: 'fir-learning-95afb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD--XXQpStgV40wRYplQHE3Uu7rIVy76t4',
    appId: '1:433354340786:ios:18ed08476d6b4099a54cab',
    messagingSenderId: '433354340786',
    projectId: 'fir-learning-95afb',
    storageBucket: 'fir-learning-95afb.appspot.com',
    androidClientId: '433354340786-s0ilr2fh7isc0qut1crtlus96prlkm2h.apps.googleusercontent.com',
    iosClientId: '433354340786-q2dv1v0p6nc5o6u33leotano51n81ota.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePractice',
  );
}
